run:
  timeout: 3m

linters-settings:
  gomnd:
    settings:
      mnd:
        ignored-numbers: "0o666,0o777"
linters:
  enable-all: true
  disable:
    # New で interface を戻り値とすることを許す。
    - ireturn
    - varnamelen
    - tagliatelle
    - nonamedreturns
    - depguard
    - containedctx
    - godox
    ## ============ deprecated ============
    - exhaustivestruct
    - exhaustruct
    - golint
    - revive
issues:
  exclude-rules:
    - path: config/config.go
      linters:
        - funlen
    - linters:
        - goerr113
      text: 'do not define dynamic errors'
    - path: (.+)_test.go
      linters:
        - funlen
        - noctx
        - gochecknoglobals
        - lll
