name: daily_check

on:
  # 手動実行できるようにする！
  workflow_dispatch:
  schedule:
    # 日本時間7時00分
    - cron: '0 22 * * *'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: checkout
        uses: actions/checkout@v4
      - name: Format check
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            exit 1
          fi

      - name: Lint
        run: go vet ./...

      - name: Install vulnerability checker
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Check vulnerabilities
        run: govulncheck -test ./...
        continue-on-error: true
