name: Run unit tests

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: account
          POSTGRES_DB: account_book
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Test
        run: make test

      - name: Install vulnerability checker
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Check vulnerabilities
        run: govulncheck -test ./...
        continue-on-error: true
